### ISSUE TITLE
Storing into database

### ISSUE THREAD

**Issue by shivam9804** [jaydeepw/avantika-university#1]
Sir, I am having a problem in sending data from one of my form using a post method i don't know where i am making mistake or my way of sending the data is wrong can please help me out.

**Comment by shivam9804** [comment]
SIr, I was able to solve the problem the issue was with the network and I also forgot to include the services in the manifest

**Comment by jaydeepw** [comment]
👍 Next time I will delay answering for 4 hours. haha

**Comment by shivam9804** [comment]
Sure and Thank you for your response
